# Generated by Django 4.1.5 on 2023-09-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='product.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savat',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='product.product_size'),
            preserve_default=False,
        ),
    ]
