# Generated by Django 4.1.5 on 2023-08-26 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_color_product_remove_product_size_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
