# Generated by Django 4.1.5 on 2023-09-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_products_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
