# Generated by Django 4.1.5 on 2023-09-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_info_products_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
